---
title: "Football Exploratory Analysis"
output:
  html_document: default
  html_notebook: default
---

```{r}
source("readDataToMemory.R")
readFootball()

library(ggplot2)
library(ggthemes)

print(dbListTables(sql_con))
```

## Pipes

```{r}
players %>%
  head
```

```{r}
players %>%
  colnames
```
```{r}
players %>%
  sapply(class)
```



## SELECT ~ select

```{r}
players %>%
  head %>%
  select(player_name, birthday)
```

```{r}
dbGetQuery(sql_con, "
SELECT player_name
,   birthday
FROM Player
LIMIT 6
")
```

## WHERE ~ filter

```{r}
# players %>%
#   filter(birthday >= "1998") %>%
#   head


player1998_txt <- "
SELECT player_name,birthday
FROM Player
WHERE birthday >= 1998
LIMIT 10
"

player1998 <-
  dbGetQuery(sql_con, player1998_txt)

player1998

```

## ORDER ~ arrange

```{r}
# players %>%
#   arrange(birthday) %>%
#   head

playerORD_txt <- "
SELECT player_name,birthday
FROM Player
ORDER BY birthday DESC
LIMIT 10
"

playerORD <-
  dbGetQuery(sql_con, playerORD_txt)

playerORD

```

## aggregators ~ summarise

```{r}
# players %>%
#   summarise(weight=mean(weight), height=mean(height))



player_sum_txt <- "
SELECT AVG(height) AS height,AVG(weight) AS weight
FROM Player
LIMIT 10
"

player_sum <-
  dbGetQuery(sql_con, player_sum_txt)

player_sum

```

## mutate

```{r}
# players %>%
#   mutate(weight_kg = weight*0.45359237) %>%
#   summarise(weight=mean(weight_kg), height=mean(height))

player_US_txt <- "
SELECT AVG(height) AS height,AVG((weight*0.45359237)) AS weight
FROM Player
LIMIT 10
"

player_US <-
  dbGetQuery(sql_con, player_US_txt)

player_US

```

## GROUP BY

```{r}
# players %>%
#   mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
#   group_by(year) %>%
#   summarise(weight=mean(height)) %>%
#   ggplot(aes(year, weight)) +
#   geom_line(colour="darkorange") +
#   theme_minimal()

year_txt <- "
SELECT AVG(height) AS ave_height, CAST(SUBSTR(birthday,1,4) AS INT) AS birth_year
FROM Player
GROUP BY birth_year
"

year <-
  dbGetQuery(sql_con, year_txt)

year%>%
  ggplot(aes(birth_year, ave_height)) +
  geom_line(colour="darkorange") +
  theme_minimal()


```
```{r}
# players %>%
#   mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
#   group_by(year) %>%
#   summarise(nsample=n()) %>%
#   ggplot(aes(year, nsample)) +
#   geom_line(colour="darkorange") +
#   theme_minimal()


year_txt <- "
SELECT CAST(SUBSTR(birthday,1,4) AS INT) AS birth_year, player_name, COUNT(1) AS number
FROM Player
GROUP BY birth_year
"

year <-
  dbGetQuery(sql_con, year_txt)

year%>%
  ggplot(aes(birth_year, number)) +
  geom_line(colour="darkorange") +
  theme_minimal()

```

```{r}
# players %>%
#   mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
#   group_by(year) %>%
#   summarise(weight=mean(height), nsamples=n()) %>%
#   filter(nsamples >= 200) %>%
#   ggplot(aes(year, weight)) +
#   geom_line(colour="darkorange") +
#   theme_minimal()

year_txt <- "
SELECT AVG(height) AS ave_height, CAST(SUBSTR(birthday,1,4) AS INT) AS birth_year, player_name, COUNT(1) AS number
FROM Player
WHERE number >= 200
"

year <-
  dbGetQuery(sql_con, year_txt)

year%>%
  ggplot(aes(birth_year, ave_height)) +
  geom_line(colour="darkorange") +
  theme_minimal()

```

Exercise

* Translate from SQL to dply or from dply to SQL
```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Match
LIMIT 6
")




```

```{r}
dbGetQuery(sql_con, "
SELECT country_id
,   COUNT(1) AS n
FROM Match
GROUP BY country_id
ORDER BY n DESC
")
```
```{r}
countries
```


```{r}
games %>%
  left_join(countries, by=c("country_id" = "id")) %>%
  select(name, home_team_api_id) %>%
  group_by(name) %>%
  summarise(teams = n_distinct(home_team_api_id)) %>%
  arrange(desc(teams))
```

```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Player_Attributes
LIMIT 6
")

```

* From where do players with higest accuracy come from?

* Add team name and translate to dplyr

```{r}
dbGetQuery(sql_con, "
SELECT stage, home_team_api_id, home_team_goal
FROM Match
WHERE country_id = 1
AND season = '2008/2009'
ORDER BY stage
")
```
